//
//  CRUD+Parameters.h
//
//  Copyright (c) 2019 andrei.dimitrief.jianu@gmail.com. All rights reserved.
//
//  The above copyright notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
//  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
//  OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
//  NON-INFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
//  HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
//  WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
//  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
//  OTHER DEALINGS IN THE SOFTWARE.
//

#ifndef CRUD_Parameters_h
#define CRUD_Parameters_h

#define BACKEND_ID_DEFAULT_VALUE @"00000000-0000-0000-0000-000000000000"
#define SYNCHRONIZATION_ID_DEFAULT_VALUE @"0"

#define FETCH_PARAMETER_SEARCH_TEXT @"fetch-parameter-search-text"
#define FETCH_PARAMETER_FILTERS @"fetch-parameter-filters"
#define FETCH_PARAMETER_SORTERS @"fetch-parameter-sorters"

#define FETCH_OPERATOR_FILTER_IGNORE_NIL @"=="
#define FETCH_OPERATOR_FILTER_EQUAL @"=="
#define FETCH_OPERATOR_FILTER_NOT_EQUAL @"<>"
#define FETCH_OPERATOR_FILTER_GREATER_THAN @">"
#define FETCH_OPERATOR_FILTER_GREATER_OR_EQUAL_THAN @">="
#define FETCH_OPERATOR_FILTER_SMALLER_THAN @"<"
#define FETCH_OPERATOR_FILTER_SMALLER_OR_EQUAL_THAN @"<="
#define FETCH_OPERATOR_FILTER_IN @"IN"

#define FETCH_OPERAND_BOOL_YES ([NSNumber numberWithBool:YES])
#define FETCH_OPERAND_BOOL_NO ([NSNumber numberWithBool:NO])

#define FETCH_OPERATOR_SORTER_ASCENDING @"YES"
#define FETCH_OPERATOR_SORTER_DESCENDING @"NO"

#define FETCH_OPERATOR_SORTER_CASE_INSENSITIVE @"YES"
#define FETCH_OPERATOR_SORTER_CASE_SENSITIVE @"NO"
#define FETCH_OPERATOR_SORTER_CASE_IGNORE @"NO"

#endif /* CRUD_Parameters_h */
